services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=cocktails'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'

  cocktail:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: cocktail
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
#    environment:
#        - 'MONGO_URI=mongodb://MONGO_INITDB_ROOT_USERNAME:MONGO_INITDB_ROOT_PASSWORD@mongodb:27017/cocktails'

volumes:
  mongodb_data:
